### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by youngjae41** [thu-uav/FlightBench#1]
Thanks youre code but error

![Screenshot from 2024-09-02 18-18-05](https://github.com/user-attachments/assets/b088d120-350e-4ca5-9580-b49d754fc43b)

**Comment by yushuang200109011** [comment]
Sorry for the wrong code. We submitted a commit to fix this error. Or you can simply replace 'pybind11_simple.cmake' and 'yaml_simple.cmake' with 'pybind11.cmake' and 'yaml.cmake', in file '/path/to/FlightBench/flightlib/CMakeLists.txt', line 46, 47.

**Comment by youngjae41** [comment]
@yushuang200109011 thanks but next error  and i'm not found benchmark_agile_autonomy code~!

# get external packages
mkdir build && cd build
cmake ..
cd ..
rm -rf build

# then, install flightgym
pip install .


Building wheels for collected packages: flightgym
  Building wheel for flightgym (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/nvidia/flightbench_ws/src/FlightBench/flightpy/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6sgj1rx2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6sgj1rx2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lkvzf5_2
       cwd: /tmp/pip-req-build-6sgj1rx2/
  Complete output (61 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 9.4.0
  -- The CXX compiler identification is GNU 9.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- ======================  !Flightmare!  ======================
  -- ======> Setup Dependencies
  -- Using system provided Eigen.
  /usr/include/eigen3
  -- Eigen3 include dir: /usr/include/eigen3
  -- Getting Pybind11...
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-6sgj1rx2/externals/pybind11-download/CMakeCache.txt is different than the directory /home/nvidia/flightbench_ws/src/FlightBench/flightlib/externals/pybind11-download where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  CMake Error at cmake/pybind11.cmake:16 (message):
    Cmake Step for Pybind11 failed: 1
  Call Stack (most recent call first):
    CMakeLists.txt:46 (include)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-6sgj1rx2/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-6sgj1rx2/setup.py", line 94, in <module>
      setup(
    File "/home/nvidia/flightbench_ws/src/FlightBench/flightpy/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/nvidia/flightbench_ws/src/FlightBench/flightpy/lib/python3.8/site-packages/wheel/_bdist_wheel.py", line 378, in run
      self.run_command("build")
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-6sgj1rx2/setup.py", line 58, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-6sgj1rx2/setup.py", line 88, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] +
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-6sgj1rx2', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-6sgj1rx2/build/lib.linux-x86_64-3.8/', '-DPYTHON_EXECUTABLE=/home/nvidia/flightbench_ws/src/FlightBench/flightpy/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for flightgym
  Running setup.py clean for flightgym
Failed to build flightgym
Installing collected packages: flightgym
    Running setup.py install for flightgym ... error
    ERROR: Command errored out with exit status 1:
     command: /home/nvidia/flightbench_ws/src/FlightBench/flightpy/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6sgj1rx2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6sgj1rx2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1parzt6a/install-record.txt --single-version-externally-managed --compile --install-headers /home/nvidia/flightbench_ws/src/FlightBench/flightpy/include/site/python3.8/flightgym
         cwd: /tmp/pip-req-build-6sgj1rx2/
    Complete output (63 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 9.4.0
    -- The CXX compiler identification is GNU 9.4.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- ======================  !Flightmare!  ======================
    -- ======> Setup Dependencies
    -- Using system provided Eigen.
    /usr/include/eigen3
    -- Eigen3 include dir: /usr/include/eigen3
    -- Getting Pybind11...
    CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-6sgj1rx2/externals/pybind11-download/CMakeCache.txt is different than the directory /home/nvidia/flightbench_ws/src/FlightBench/flightlib/externals/pybind11-download where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
    CMake Error at cmake/pybind11.cmake:16 (message):
      Cmake Step for Pybind11 failed: 1
    Call Stack (most recent call first):
      CMakeLists.txt:46 (include)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-6sgj1rx2/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6sgj1rx2/setup.py", line 94, in <module>
        setup(
      File "/home/nvidia/flightbench_ws/src/FlightBench/flightpy/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/nvidia/flightbench_ws/src/FlightBench/flightpy/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-6sgj1rx2/setup.py", line 58, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-6sgj1rx2/setup.py", line 88, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] +
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-6sgj1rx2', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-6sgj1rx2/build/lib.linux-x86_64-3.8/', '-DPYTHON_EXECUTABLE=/home/nvidia/flightbench_ws/src/FlightBench/flightpy/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/nvidia/flightbench_ws/src/FlightBench/flightpy/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6sgj1rx2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6sgj1rx2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1parzt6a/install-record.txt --single-version-externally-managed --compile --install-headers /home/nvidia/flightbench_ws/src/FlightBench/flightpy/include/site/python3.8/flightgym Check the logs for full command output.

**Comment by youngjae41** [comment]
@yushuang200109011 sorry

 i found benchmark_agile_autonomy code
 but flightgym install error

**Comment by yushuang200109011** [comment]
@youngjae41 Sorry, for `pybind.cmake` script will automatically download external dependencies, you may need to clean the flightlib/external folder and then run `pip install .`. Now there's no need for manually getting external libs. The installation docs have been updated.

**Comment by youngjae41** [comment]
@yushuang200109011 ok and then i donwload https://github.com/thu-uav/benchmark_agile_autonomy this file 

Does this file also need to be installed in the following way? 

export ROS_VERSION=noetic
mkdir agile_autonomy_ws
cd agile_autonomy_ws
export CATKIN_WS=./catkin_aa
mkdir -p $CATKIN_WS/src
cd $CATKIN_WS
catkin init
catkin config --extend /opt/ros/$ROS_VERSION
catkin config --merge-devel
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fdiagnostics-color
cd src

git clone git@github.com:uzh-rpg/agile_autonomy.git
vcs-import < agile_autonomy/dependencies.yaml
cd rpg_mpl_ros
git submodule update --init --recursive

#install extra dependencies (might need more depending on your OS)
sudo apt-get install libqglviewer-dev-qt5

# Install external libraries for rpg_flightmare
sudo apt install -y libzmqpp-dev libeigen3-dev libglfw3-dev libglm-dev

# Install dependencies for rpg_flightmare renderer
sudo apt install -y libvulkan1 vulkan-utils gdb

# Add environment variables (Careful! Modify path according to your local setup)
echo 'export RPGQ_PARAM_DIR=/home/<path/to/>catkin_aa/src/rpg_flightmare' >> ~/.bashrc


If I run simulation.sh without installing it, the following error occurs

Resource not found: agile_autonomy
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/nvidia/flightbench_ws/src/FlightBench/dep/catkin_boost_python_buildtool/catkin_boost_python_buildtool
ROS path [2]=/home/nvidia/flightbench_ws/src/FlightBench/dep/catkin_simple
ROS path [3]=/home/nvidia/flightbench_ws/src/FlightBench/dep/catkin_boost_python_buildtool/catkin_boost_python_buildtool_test
ROS path [4]=/home/nvidia/flightbench_ws/src/FlightBench/dep/eigen_catkin
ROS path [5]=/home/nvidia/flightbench_ws/src/FlightBench/flightlib
ROS path [6]=/home/nvidia/flightbench_ws/src/FlightBench/flightrender
ROS path [7]=/home/nvidia/flightbench_ws/src/FlightBench/dep/gflags_catkin
ROS path [8]=/home/nvidia/flightbench_ws/src/FlightBench/dep/glog_catkin
ROS path [9]=/home/nvidia/flightbench_ws/src/FlightBench/dep/eigen_check
ROS path [10]=/home/nvidia/flightbench_ws/src/FlightBench/dep/mav_comm/mav_comm
ROS path [11]=/home/nvidia/flightbench_ws/src/FlightBench/dep/mav_comm/mav_msgs
ROS path [12]=/home/nvidia/flightbench_ws/src/FlightBench/dep/mav_comm/mav_planning_msgs
ROS path [13]=/home/nvidia/flightbench_ws/src/FlightBench/dep/mav_comm/mav_state_machine_msgs
ROS path [14]=/home/nvidia/flightbench_ws/src/FlightBench/dep/mav_comm/mav_system_msgs
ROS path [15]=/home/nvidia/flightbench_ws/src/FlightBench/dep/minimum_jerk_trajectories
ROS path [16]=/home/nvidia/flightbench_ws/src/FlightBench/dep/minkindr/minkindr
ROS path [17]=/home/nvidia/flightbench_ws/src/FlightBench/dep/minkindr_ros/minkindr_conversions
ROS path [18]=/home/nvidia/flightbench_ws/src/FlightBench/dep/numpy_eigen
ROS path [19]=/home/nvidia/flightbench_ws/src/FlightBench/dep/minkindr/minkindr_python
ROS path [20]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/quad_launch_files
ROS path [21]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_common/quadrotor_msgs
ROS path [22]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_common/quadrotor_common
ROS path [23]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/bridges/mavros_bridge
ROS path [24]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/trajectory_planning/polynomial_trajectories
ROS path [25]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/control/position_controller
ROS path [26]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_comm
ROS path [27]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_control
ROS path [28]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_description
ROS path [29]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_evaluation
ROS path [30]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_gazebo_plugins
ROS path [31]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_gazebo
ROS path [32]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_joy_interface
ROS path [33]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rotors_simulator
ROS path [34]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rpg_common
ROS path [35]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/simulation/rpg_rotors_interface
ROS path [36]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rpg_single_board_io
ROS path [37]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/gui/rqt_quad_gui
ROS path [38]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rotors_simulator/rqt_rotors
ROS path [39]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/bridges/sbus_bridge
ROS path [40]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/utils/manual_flight_assistant
ROS path [41]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_common/state_predictor
ROS path [42]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/trajectory_planning/trajectory_ext
ROS path [43]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/trajectory_planning/trajectory_generation_helper
ROS path [44]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/control/autopilot
ROS path [45]=/home/nvidia/flightbench_ws/src/FlightBench/flightbench
ROS path [46]=/home/nvidia/flightbench_ws/src/FlightBench/flightros
ROS path [47]=/home/nvidia/flightbench_ws/src/FlightBench/dep/rpg_mpc
ROS path [48]=/home/nvidia/flightbench_ws/src/FlightBench/dep/quadrotor_control/utils/trajectory_visualizer
ROS path [49]=/opt/ros/noetic/share
The traceback for the exception was written to the log file

**Comment by yushuang200109011** [comment]
Just clone the git repo to the src directory and compile the workspace according to the instruction (https://thu-uav.github.io/FlightBench/#installation, the *install baselines* section). If you have other questions, feel free to give us feedback.

**Comment by youngjae41** [comment]
@yushuang200109011 


![Screenshot from 2024-09-09 13-30-31](https://github.com/user-attachments/assets/391214d7-a33a-49dd-b1cd-3b24389e247d)

and i can't found ckpt file
